name: Deploy to Koyeb

on:
  push:
    branches:
      - main
      - module-2-exercise
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-22.04
    steps:
      - name: Configure Koyeb credentials
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy service from Git repository
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: modul-2-ci-cd-devops
          service-name: eshop-web
          service-instance-type: nano
          service-ports: "8080:http"
          service-routes: "/:8080"
          service-checks: "8080:http:/"
          git-builder: docker
          git-docker-dockerfile: Dockerfile
          git-branch: ${{ github.ref_name }}
          git-sha: ${{ github.sha }}
